[package]
name = "blueprint-scm"
version = "0.0.1"
edition = "2021"

[dependencies]
fxhash = "0.2"
nom = "7.1"
thiserror = "1.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["cargo"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
strip = true

[[bin]]
name = "blueprint"
path = "src/main.rs"
